

import { Drill, User } from '../types';
import * as dataService from '../services/localDataService';
import { simpleHash } from '../services/localAuthService';

export const seedInitialData = (): void => {
    const currentBank = dataService.getDrillBank();
    if (currentBank.length === 0) {
        dataService.saveDrillBank(SEED_DRILLS);
        console.log('Initial drill data seeded.');
    }

    const currentUsers = dataService.getUsers();
    if (currentUsers.length === 0) {
        const adminUser: User = {
            id: 'user_admin_001',
            email: 'admin@proevals.com',
            passwordHash: simpleHash('admin'),
            name: 'Admin',
            pmLevel: 'Principal - Staff PM (9+ Yrs)',
            plan: 'Teams',
            createdAt: new Date().toISOString()
        };
        dataService.addUser(adminUser);
        console.log('Seeded initial admin user (email: admin@proevals.com, pass: admin).');
    }
};

export const seedLeaderboardData = (): void => {
    const users = dataService.getUsers();
    if (users.length < 5) {
        console.warn("Not enough users to seed leaderboard. Seeding with mock data.");
        const mockData = [
            { name: "Alex T.", calibrationScore: 92, drillsCompleted: 45 },
            { name: "Sarah L.", calibrationScore: 89, drillsCompleted: 51 },
            { name: "Chris J.", calibrationScore: 88, drillsCompleted: 38 },
            { name: "Priya S.", calibrationScore: 85, drillsCompleted: 42 },
            { name: "Ben K.", calibrationScore: 81, drillsCompleted: 35 },
            { name: "Maria G.", calibrationScore: 79, drillsCompleted: 60 },
            { name: "Leo F.", calibrationScore: 77, drillsCompleted: 25 },
        ];
        dataService.saveLeaderboard(mockData);
        return;
    }

    const leaderboardData = users.slice(0, 10).map(user => ({
        userId: user.id,
        name: user.name,
        calibrationScore: Math.floor(Math.random() * (95 - 70 + 1)) + 70, 
        drillsCompleted: Math.floor(Math.random() * (50 - 10 + 1)) + 10,
    })).sort((a, b) => b.calibrationScore - a.calibrationScore);

    dataService.saveLeaderboard(leaderboardData);
    console.log('Mock leaderboard data seeded from existing users.');
};


export const SEED_DRILLS: Drill[] = [
    // Associate PM Drills (5)
    {
      "drill_id": "seed_001",
      "title": "Launch Timing Dilemma",
      "target_pm_level": "Associate PM (0-2 Yrs)",
      "skill_category": "Execution & Prioritization",
      "core_scenario_text": "Your team is close to launching a new feature, but a minor but noticeable UI bug was just found. The marketing campaign is scheduled to start next week. Delaying the launch will misalign with marketing, but launching with the bug could lead to some user complaints and a poor first impression. The bug fix is estimated to take 3-4 days.",
      "stakeholder_1_role": "Engineering Lead",
      "stakeholder_1_quote": "We can ship now and patch it next week. The bug is cosmetic and doesn't break core functionality. Let's not hold up the release for this.",
      "stakeholder_2_role": "Marketing Manager",
      "stakeholder_2_quote": "We have our entire launch campaign, influencers, and press releases scheduled for next Tuesday. Any delay will cost us momentum and budget.",
      "stakeholder_3_role": "Support Manager",
      "stakeholder_3_quote": "My team is already stretched thin. If we launch with a known bug, even a small one, it will increase our ticket volume. I'd strongly prefer we fix it first.",
      "option_a": "Launch on time with the known bug and schedule a fast-follow patch for the next week.",
      "option_b": "Delay the launch by one week to fix the bug, and work with marketing to adjust their campaign schedule.",
      "option_c": "Launch on time, but disable the specific part of the UI where the bug appears, reducing the feature's scope.",
      "option_d": "Push the engineering team to work overtime to fix the bug before the scheduled launch date.",
      "optimal_choice": "A",
      "expert_analysis_text": "For an Associate PM, showing a bias for action and managing a fast-follow is a key skill. Option A balances business momentum with technical debt, a common trade-off. It acknowledges the marketing constraint's importance while creating a clear plan to address the issue without causing team burnout. It demonstrates trust in the engineering team's assessment of the bug's severity and their ability to patch it quickly, which is crucial for building good rapport.",
      "rationale_for_a": "This is the optimal choice. It respects the marketing timeline and business momentum while having a clear, low-risk plan to address the quality issue promptly after launch.",
      "rationale_for_b": "Delaying is a safe but costly option. It misses a key business window and can signal an overly cautious culture. At this bug's low severity, the delay is not justified.",
      "rationale_for_c": "Reducing scope at the last minute creates a confusing user experience and may devalue the launch. It's often better to launch fully and patch than to launch partially.",
      "rationale_for_d": "Forcing overtime for a minor bug is poor leadership. It burns out the team, damages morale, and sets a precedent for 'crunch culture' over sustainable planning and execution.",
      "peer_data_a": 42,
      "peer_data_b": 28,
      "peer_data_c": 15,
      "peer_data_d": 15
    },
    {
      "drill_id": "seed_003",
      "title": "Feature Deadline Conflict",
      "target_pm_level": "Associate PM (0-2 Yrs)",
      "skill_category": "Stakeholder Management",
      "core_scenario_text": "You're managing a mobile app feature launch scheduled for next sprint. QA discovered critical bugs that need two extra days to fix properly. Marketing has already announced the launch date publicly, and your engineering team is pushing back on working overtime. You need to decide how to handle this sprint delivery conflict.",
      "stakeholder_1_role": "Engineering Lead",
      "stakeholder_1_quote": "We can rush the fixes in one day, but it'll introduce technical debt and potential new bugs.",
      "stakeholder_2_role": "Marketing Manager",
      "stakeholder_2_quote": "We've already promoted this launch date across all channels. Delaying now will hurt our credibility with users.",
      "stakeholder_3_role": "QA Lead",
      "stakeholder_3_quote": "These bugs affect core functionality. Shipping without proper fixes will generate support tickets and negative reviews.",
      "option_a": "Ship on schedule with known bugs and plan a hotfix release within 48 hours.",
      "option_b": "Delay the full feature launch by one week and communicate the delay transparently to users.",
      "option_c": "Launch a limited beta version to select users while fixing bugs for full public release.",
      "option_d": "Negotiate with engineering to work overtime this weekend to meet the original deadline.",
      "optimal_choice": "C",
      "expert_analysis_text": "Option C provides the best compromise for an Associate PM learning stakeholder management. It honors marketing's commitment while maintaining quality standards. A limited beta allows you to gather user feedback, demonstrate progress to stakeholders, and buy time for proper bug fixes without sacrificing the entire launch timeline or product quality.",
      "rationale_for_a": "Shipping known bugs risks user experience and creates support burden. This approach prioritizes short-term marketing goals over long-term product quality.",
      "rationale_for_b": "While quality-focused, completely delaying damages marketing credibility and misses learning opportunity about managing competing priorities in real-time.",
      "rationale_for_c": "This choice balances stakeholder needs effectively, maintains launch momentum while ensuring quality, and provides valuable user feedback for improvement.",
      "rationale_for_d": "Relying on overtime sets poor precedent for team dynamics and doesn't address the root cause of timeline estimation issues.",
      "peer_data_a": 20,
      "peer_data_b": 25,
      "peer_data_c": 40,
      "peer_data_d": 15
    },
    {
      "drill_id": "seed_004",
      "title": "Data Privacy Trade-off",
      "target_pm_level": "Associate PM (0-2 Yrs)",
      "skill_category": "Technical Acumen",
      "core_scenario_text": "Your e-commerce mobile app needs to implement better fraud detection to reduce chargebacks. Security team recommends collecting location data and device fingerprinting, but legal warns this could violate privacy regulations in some regions. Customer support reports increasing fraud complaints affecting user trust.",
      "stakeholder_1_role": "Security Engineer",
      "stakeholder_1_quote": "Without device fingerprinting, we can't catch repeat fraudsters. Our current fraud rate is 3x industry average.",
      "stakeholder_2_role": "Legal Counsel",
      "stakeholder_2_quote": "GDPR compliance requires explicit consent for location tracking. This could expose us to regulatory fines if implemented incorrectly.",
      "stakeholder_3_role": "Customer Success Lead",
      "stakeholder_3_quote": "Legitimate customers are getting frustrated with false fraud flags. We need better detection without blocking real purchases.",
      "option_a": "Implement full fraud detection with location tracking and device fingerprinting globally.",
      "option_b": "Use basic fraud detection only, avoiding any privacy-sensitive data collection methods.",
      "option_c": "Deploy region-specific fraud detection with privacy compliance safeguards built in.",
      "option_d": "Launch fraud detection in pilot markets first to test impact before broader rollout.",
      "optimal_choice": "C",
      "expert_analysis_text": "Option C balances security needs with legal compliance effectively. Regional customization shows sophisticated understanding of global product management while addressing fraud concerns responsibly. This approach demonstrates Associate PM ability to navigate competing requirements without compromising either security or compliance, while maintaining user trust through transparent privacy practices.",
      "rationale_for_a": "Ignoring regional privacy laws creates significant legal risk and potential regulatory penalties that could harm the business long-term.",
      "rationale_for_b": "Basic fraud detection fails to address the core security problem and doesn't protect legitimate customers from fraudulent activity impact.",
      "rationale_for_c": "This solution addresses fraud concerns while respecting privacy regulations, showing balanced stakeholder management and compliance awareness.",
      "rationale_for_d": "Pilot testing delays fraud protection for most users and doesn't resolve the underlying privacy compliance requirements.",
      "peer_data_a": 15,
      "peer_data_b": 20,
      "peer_data_c": 45,
      "peer_data_d": 20
    },
    {
      "drill_id": "seed_005",
      "title": "Feature Launch Delay",
      "target_pm_level": "Associate PM (0-2 Yrs)",
      "skill_category": "Execution & Prioritization",
      "core_scenario_text": "Your team built a new social sharing feature for your fitness app, but QA found accessibility issues that affect screen reader users. The feature is scheduled to launch in three days alongside a major marketing campaign. Engineering estimates five days to fix the accessibility problems properly.",
      "stakeholder_1_role": "QA Lead",
      "stakeholder_1_quote": "The accessibility violations are serious. Visually impaired users can't access core sharing functionality at all.",
      "stakeholder_2_role": "Marketing Director",
      "stakeholder_2_quote": "We've invested $50K in this campaign launch. Delaying now means losing our promotional slots and budget.",
      "stakeholder_3_role": "Engineering Manager",
      "stakeholder_3_quote": "Quick fixes are possible but won't meet accessibility standards. Proper implementation needs five full days minimum.",
      "option_a": "Launch on schedule with accessibility issues and promise to fix them in next sprint.",
      "option_b": "Delay the entire launch by one week to ensure full accessibility compliance.",
      "option_c": "Launch without the social sharing feature and add it in the following release.",
      "option_d": "Launch with temporary accessibility workarounds while engineering completes proper fixes.",
      "optimal_choice": "B",
      "expert_analysis_text": "Option B demonstrates commitment to inclusive design and legal compliance. Accessibility isn't optional—it's both an ethical responsibility and legal requirement. While the marketing investment is significant, launching with accessibility violations risks discrimination lawsuits and excludes users permanently. This choice shows mature product thinking about long-term brand reputation over short-term marketing goals.",
      "rationale_for_a": "Shipping known accessibility violations violates ADA compliance and discriminates against disabled users, creating legal and ethical risks.",
      "rationale_for_b": "This choice prioritizes inclusive design and legal compliance while maintaining product quality, demonstrating responsible product management.",
      "rationale_for_c": "Removing core functionality disappoints all users and wastes engineering investment while still requiring marketing campaign changes.",
      "rationale_for_d": "Temporary workarounds often become permanent, creating technical debt and still failing to serve disabled users properly.",
      "peer_data_a": 25,
      "peer_data_b": 40,
      "peer_data_c": 15,
      "peer_data_d": 20
    },
    {
      "drill_id": "seed_006",
      "title": "User Onboarding Length",
      "target_pm_level": "Associate PM (0-2 Yrs)",
      "skill_category": "User Research & Empathy",
      "core_scenario_text": "Your project management SaaS tool has a comprehensive 7-step onboarding process. Analytics show 60% of users complete it, but support reports these users are more engaged long-term. Growth team wants to reduce it to 3 steps to improve completion rates and quick wins.",
      "stakeholder_1_role": "Growth Analyst",
      "stakeholder_1_quote": "Shorter onboarding will boost our activation metrics. Most users abandon after step 4, so we're losing potential customers.",
      "stakeholder_2_role": "Customer Success Manager",
      "stakeholder_2_quote": "Users who complete full onboarding have 40% higher retention rates. They understand the product better from day one.",
      "stakeholder_3_role": "UX Designer",
      "stakeholder_3_quote": "We can make onboarding progressive - show core features first, then introduce advanced ones based on usage patterns.",
      "option_a": "Keep the current 7-step onboarding process unchanged to maintain user education quality.",
      "option_b": "Reduce onboarding to 3 essential steps and eliminate advanced feature introductions.",
      "option_c": "Create a progressive onboarding system that starts simple and adds complexity over time.",
      "option_d": "A/B test different onboarding lengths to measure impact on activation and retention.",
      "optimal_choice": "C",
      "expert_analysis_text": "Option C provides the optimal balance between initial simplicity and comprehensive education. Progressive onboarding addresses both growth and retention concerns by reducing initial friction while ensuring users learn advanced features when ready. This approach demonstrates sophisticated UX thinking and shows understanding that user education and activation aren't mutually exclusive goals.",
      "rationale_for_a": "Maintaining status quo ignores activation rate problems and doesn't address the clear user drop-off pattern in analytics.",
      "rationale_for_b": "Eliminating advanced features from onboarding may improve initial metrics but reduces long-term user success and retention.",
      "rationale_for_c": "Progressive onboarding optimizes for both activation and retention, providing immediate value while enabling deeper engagement over time.",
      "rationale_for_d": "A/B testing is valuable but doesn't provide an immediate solution to the conflicting stakeholder needs and metrics.",
      "peer_data_a": 10,
      "peer_data_b": 25,
      "peer_data_c": 50,
      "peer_data_d": 15
    },

    // Product Manager Drills (5)
    {
      "drill_id": "seed_024",
      "title": "Resource Allocation Crisis",
      "target_pm_level": "Product Manager (2-5 Yrs)",
      "skill_category": "Execution & Prioritization",
      "core_scenario_text": "Your team has bandwidth for two major initiatives this quarter: rebuilding the payment system to reduce transaction failures or launching the long-awaited API for enterprise customers. Both initiatives are critical, but engineering can only deliver one properly. The payment issues affect 15% of transactions, while API delays are blocking three major enterprise deals worth $2M annually.",
      "stakeholder_1_role": "VP of Engineering",
      "stakeholder_1_quote": "Both projects are complex. Splitting the team guarantees we'll deliver neither on time and both will have quality issues.",
      "stakeholder_2_role": "Head of Sales",
      "stakeholder_2_quote": "Enterprise customers are threatening to walk. We've promised API access for eight months. Our credibility is on the line.",
      "stakeholder_3_role": "Customer Support Director",
      "stakeholder_3_quote": "Payment failures generate 40% of our support tickets. It's hurting customer trust and our support team's morale.",
      "option_a": "Prioritize the payment system rebuild to improve core user experience and reduce support burden.",
      "option_b": "Focus on API launch to secure enterprise revenue and fulfill sales commitments to major clients.",
      "option_c": "Deliver basic versions of both initiatives and iterate based on initial feedback and metrics.",
      "option_d": "Negotiate with stakeholders to extend timeline and properly sequence both initiatives across two quarters.",
      "optimal_choice": "A",
      "expert_analysis_text": "Option A addresses the foundation that affects all users. Payment reliability is table stakes for any transactional product—15% failure rate represents significant revenue loss and user churn. While enterprise deals are valuable, unreliable core functionality undermines the entire platform. Fixing payments first enables sustainable growth and provides a stable foundation for enterprise features.",
      "rationale_for_a": "Payment reliability affects all users and is fundamental to business trust. Fixing core functionality provides stable foundation for future features.",
      "rationale_for_b": "While enterprise revenue is important, building on unstable foundations risks losing both current users and enterprise customers long-term.",
      "rationale_for_c": "Partial delivery of complex systems often results in technical debt and user frustration without solving either problem effectively.",
      "rationale_for_d": "Timeline negotiations may work but don't address immediate competitive pressure and ongoing user impact from payment failures.",
      "peer_data_a": 45,
      "peer_data_b": 30,
      "peer_data_c": 15,
      "peer_data_d": 10
    }, 
    {
      "drill_id": "seed_025",
      "title": "Cross-Platform Strategy Conflict",
      "target_pm_level": "Product Manager (2-5 Yrs)",
      "skill_category": "Strategic Thinking",
      "core_scenario_text": "Your productivity app has grown to equal usage across mobile and web platforms, but user behaviors differ significantly. Mobile users prefer quick task creation and notifications, while web users want detailed project management and reporting. Leadership wants platform parity, but your user research shows each platform serves different use cases optimally.",
      "stakeholder_1_role": "Head of Product",
      "stakeholder_1_quote": "Brand consistency requires feature parity. Users should get the same experience regardless of how they access our product.",
      "stakeholder_2_role": "UX Research Manager",
      "stakeholder_2_quote": "Our studies show mobile users get frustrated with complex interfaces, while web users feel limited by simplified designs.",
      "stakeholder_3_role": "Engineering Director",
      "stakeholder_3_quote": "Maintaining different feature sets doubles our development and testing complexity. Shared components reduce technical debt.",
      "option_a": "Maintain platform-specific experiences optimized for each user context and behavior pattern.",
      "option_b": "Standardize features across platforms to ensure brand consistency and reduce development complexity.",
      "option_c": "Create adaptive interfaces that adjust complexity based on user preferences within each platform.",
      "option_d": "Focus development resources on the highest-performing platform and minimize investment in the other.",
      "optimal_choice": "A",
      "expert_analysis_text": "Option A recognizes that different platforms serve different user contexts and workflows. Forcing parity ignores fundamental UX principles about context-appropriate design. Users choose platforms based on their needs—mobile for quick actions, web for deep work. Platform-optimized experiences drive higher engagement and better outcomes than forced consistency.",
      "rationale_for_a": "Platform-specific optimization respects user context and behavior patterns, leading to higher engagement and satisfaction on each platform.",
      "rationale_for_b": "Forcing parity compromises user experience on both platforms to serve abstract consistency goals rather than user needs.",
      "rationale_for_c": "Adaptive interfaces add significant complexity without addressing the fundamental difference in platform contexts and user expectations.",
      "rationale_for_d": "Abandoning successful platforms wastes existing user base and limits product reach and market opportunities.",
      "peer_data_a": 40,
      "peer_data_b": 25,
      "peer_data_c": 20,
      "peer_data_d": 15
    }, 
    {
      "drill_id": "seed_026",
      "title": "Data Migration Complexity",
      "target_pm_level": "Product Manager (2-5 Yrs)",
      "skill_category": "Technical Acumen",
      "core_scenario_text": "Your customer data platform needs to migrate 10TB of customer data to a new architecture for better performance and GDPR compliance. The migration affects all product features for six weeks during development, with two weeks of limited functionality. Marketing has planned major campaigns during this period, and customer success is concerned about user experience disruption.",
      "stakeholder_1_role": "CTO",
      "stakeholder_1_quote": "This migration is critical for scalability and compliance. Delaying increases technical debt and regulatory risk significantly.",
      "stakeholder_2_role": "VP of Marketing",
      "stakeholder_2_quote": "We've committed $500K in campaign spend during this period. Moving campaigns means losing seasonal opportunities and budget efficiency.",
      "stakeholder_3_role": "Customer Success VP",
      "stakeholder_3_quote": "Any service disruption during high-usage periods risks customer churn and damages relationships we've built over years.",
      "option_a": "Proceed with migration as planned and communicate transparently with customers about temporary limitations.",
      "option_b": "Delay migration until after marketing campaigns to avoid disrupting customer experience during high activity.",
      "option_c": "Implement phased migration over longer timeline to minimize user-facing disruption each period.",
      "option_d": "Build parallel systems to maintain full functionality during migration, accepting higher infrastructure costs.",
      "optimal_choice": "C",
      "expert_analysis_text": "Option C balances technical necessity with business continuity. Phased migration spreads risk and impact over time, allowing teams to address issues incrementally while maintaining customer relationships. This approach demonstrates mature product thinking about complex technical changes—prioritizing sustainable transformation over speed while managing stakeholder concerns systematically.",
      "rationale_for_a": "While transparency is valuable, proceeding with full disruption during peak usage risks significant customer satisfaction and retention issues.",
      "rationale_for_b": "Delaying compliance and scalability improvements increases technical and regulatory risks that could be more costly than campaign timing.",
      "rationale_for_c": "Phased approach balances technical progress with business continuity, reducing risk while maintaining customer relationships and campaign effectiveness.",
      "rationale_for_d": "Parallel systems eliminate user impact but significantly increase infrastructure costs and technical complexity during transition period.",
      "peer_data_a": 20,
      "peer_data_b": 15,
      "peer_data_c": 50,
      "peer_data_d": 15
    }, 
    {
      "drill_id": "seed_027",
      "title": "Freemium Model Optimization",
      "target_pm_level": "Product Manager (2-5 Yrs)",
      "skill_category": "Growth & Monetization",
      "core_scenario_text": "Your design collaboration tool's freemium model isn't converting well—only 8% of free users upgrade to paid plans. Free users get unlimited personal projects but limited team features. Analysis shows free users who collaborate convert at 25% rates, but most free users work alone. You need to redesign the freemium boundaries to improve conversion while maintaining user acquisition.",
      "stakeholder_1_role": "Revenue Operations Manager",
      "stakeholder_1_quote": "Our conversion rate is half the industry standard. We need better paywalls that demonstrate premium value without frustrating users.",
      "stakeholder_2_role": "Growth Marketing Lead",
      "stakeholder_2_quote": "Restricting free features too much will hurt our viral growth loop and reduce word-of-mouth acquisition from satisfied users.",
      "stakeholder_3_role": "User Research Director",
      "stakeholder_3_quote": "Solo users rarely see collaboration value until they try it. We need to create opportunities for collaborative experiences.",
      "option_a": "Limit free users to 3 personal projects and 1 shared project to encourage collaboration and premium upgrades.",
      "option_b": "Keep unlimited personal projects but add premium-only advanced features like version history and advanced export options.",
      "option_c": "Introduce collaboration invitations for free users with time-limited team access to demonstrate premium value.",
      "option_d": "Segment freemium limits by user type—individual creators get different limits than team-oriented users.",
      "optimal_choice": "C",
      "expert_analysis_text": "Option C creates conversion opportunities by giving users taste of premium collaboration features without permanent access. Time-limited team features let solo users experience the value they're missing while maintaining the free tier's acquisition power. This 'try before you buy' approach directly addresses the insight that collaborative users convert at higher rates.",
      "rationale_for_a": "Project limits may reduce user acquisition and don't necessarily drive users toward the high-converting collaboration features.",
      "rationale_for_b": "Advanced features alone don't address the core conversion insight about collaboration being the primary driver of premium upgrades.",
      "rationale_for_c": "Time-limited collaboration access creates conversion motivation by demonstrating premium value while maintaining free tier acquisition benefits.",
      "rationale_for_d": "User segmentation adds complexity and may confuse potential users about what they can access in the free tier.",
      "peer_data_a": 25,
      "peer_data_b": 20,
      "peer_data_c": 40,
      "peer_data_d": 15
    }, 
    {
      "drill_id": "seed_028",
      "title": "Feature Deprecation Dilemma",
      "target_pm_level": "Product Manager (2-5 Yrs)",
      "skill_category": "Stakeholder Management",
      "core_scenario_text": "Your analytics dashboard includes a legacy reporting feature used by only 12% of users, but these users generate 35% of your revenue. The feature requires significant maintenance, blocks modern architecture improvements, and prevents mobile optimization. Engineering estimates keeping it costs 20% of development capacity, while rebuilding it would take an entire quarter.",
      "stakeholder_1_role": "VP of Customer Success",
      "stakeholder_1_quote": "These power users are our most valuable customers. Removing features they rely on daily will damage relationships and drive churn.",
      "stakeholder_2_role": "Engineering VP",
      "stakeholder_2_quote": "This legacy code blocks platform modernization and team productivity. We can't innovate while maintaining outdated systems indefinitely.",
      "stakeholder_3_role": "Head of Sales",
      "stakeholder_3_quote": "Enterprise prospects specifically ask about advanced reporting. It's a key differentiator even if most users don't need it.",
      "option_a": "Deprecate the legacy feature and help high-value users transition to alternative solutions or workflows.",
      "option_b": "Rebuild the feature with modern architecture to maintain functionality while enabling platform improvements.",
      "option_c": "Keep the legacy feature as-is but stop all new development to focus resources on core platform evolution.",
      "option_d": "Create a premium add-on version of advanced reporting to justify the development and maintenance costs.",
      "optimal_choice": "B",
      "expert_analysis_text": "Option B protects high-value customer relationships while addressing technical debt concerns. Rebuilding maintains competitive differentiation and customer satisfaction while unblocking platform modernization. The quarter investment pays long-term dividends in customer retention, sales positioning, and technical agility—especially given the revenue concentration among these users.",
      "rationale_for_a": "Removing features used by 35% of revenue-generating customers risks significant churn and competitive disadvantage in enterprise sales.",
      "rationale_for_b": "Rebuilding preserves customer value and competitive advantage while solving technical debt issues, justified by revenue concentration.",
      "rationale_for_c": "Maintaining legacy systems without evolution creates growing technical debt and eventually forces more expensive future decisions.",
      "rationale_for_d": "Converting existing functionality to premium add-ons may alienate current users and complicate pricing structure unnecessarily.",
      "peer_data_a": 15,
      "peer_data_b": 50,
      "peer_data_c": 20,
      "peer_data_d": 15
    },

    // Senior PM Drills (5)
    {
      "drill_id": "seed_002",
      "title": "Strategic Partnership Opportunity",
      "target_pm_level": "Senior PM (5+ Yrs)",
      "skill_category": "Strategic Thinking",
      "core_scenario_text": "A major player in an adjacent market wants to partner for a deep integration. The integration would require significant engineering resources (2 engineers for 3 months), potentially delaying your existing roadmap for Q3. However, the partnership could unlock a new, large user segment and create a strong competitive moat. The partner is pushing for a quick commitment.",
      "stakeholder_1_role": "VP of Engineering",
      "stakeholder_1_quote": "This is a huge, unplanned request. Pulling two engineers will definitely cause us to miss our Q3 roadmap goals for core product improvements. The proposed integration is also technically complex.",
      "stakeholder_2_role": "Director of Business Development",
      "stakeholder_2_quote": "This is a game-changing opportunity. This partner rarely does deals like this. If we don't move fast, they'll go to our competitor. We need to show we're committed and get this done.",
      "stakeholder_3_role": "VP of Product",
      "stakeholder_3_quote": "I see the strategic upside, but I'm worried about derailing our core product strategy. Are we sure this is the right move for us long-term, or is it just a shiny object?",
      "option_a": "Commit fully to the partnership, re-prioritize the roadmap, and dedicate the required engineering resources immediately.",
      "option_b": "Decline the partnership to stay focused on the existing, validated roadmap and core product improvements.",
      "option_c": "Propose a smaller, phased integration (MVP) to the partner, which requires fewer resources, to test the value of the partnership first.",
      "option_d": "Tell the partner you're interested but need to complete your Q3 roadmap first, asking them to wait a quarter.",
      "optimal_choice": "C",
      "expert_analysis_text": "A Senior PM must balance strategic opportunities with execution realities. Option C is the strongest choice as it de-risks a major strategic bet. It allows the company to test the core hypotheses of the partnership (user adoption, technical feasibility, strategic value) with a much smaller investment. This data-driven approach provides a solid foundation for a larger commitment later, satisfies the partner's need for momentum, and minimizes disruption to the current roadmap, showing mature product leadership.",
      "rationale_for_a": "Going all-in is a high-risk, high-reward bet. Without validating the partnership's potential, you risk significant resources on an unproven initiative, a common pitfall for even senior PMs.",
      "rationale_for_b": "Being too rigid with the roadmap can mean missing out on transformative opportunities. A key senior PM skill is knowing when to deviate from the plan for a strategic advantage.",
      "rationale_for_c": "This is the optimal choice. It's a classic product thinking approach: de-risk, learn, and iterate. It shows strategic thinking combined with pragmatic execution.",
      "rationale_for_d": "Asking a motivated strategic partner to wait three months is unrealistic in a competitive market. This is effectively a 'no' and would likely result in them approaching a competitor.",
      "peer_data_a": 25,
      "peer_data_b": 15,
      "peer_data_c": 45,
      "peer_data_d": 15,
      "strategic_alternative": "A",
      "strategic_alternative_rationale": "Committing fully demonstrates strong conviction and can capture the opportunity before competitors. In a fast-moving market, decisiveness can be a key advantage. This choice is appropriate if the strategic alignment is exceptionally strong and the potential upside justifies the roadmap disruption."
    },
    {
      "drill_id": "seed_044",
      "title": "Platform API Strategy Decision",
      "target_pm_level": "Senior PM (5+ Yrs)",
      "skill_category": "Strategic Thinking",
      "core_scenario_text": "Your fintech platform serves 2M users but growth has plateaued. Engineering wants to build a comprehensive API platform to enable third-party integrations, requiring 18 months of development. Current revenue is $50M annually with 15% growth declining to 8%. Competitors are launching similar initiatives.",
      "stakeholder_1_role": "VP of Engineering",
      "stakeholder_1_quote": "This API platform will future-proof us and create new revenue streams through partnerships.",
      "stakeholder_2_role": "CFO",
      "stakeholder_2_quote": "We need immediate revenue growth; this 18-month investment delays our profitability goals significantly.",
      "stakeholder_3_role": "Head of Business Development",
      "stakeholder_3_quote": "Partners are asking for integrations now; without APIs we're losing deals daily.",
      "option_a": "Full API platform development with dedicated 12-person team over 18 months",
      "option_b": "Phased approach: core APIs first, then expand based on partner demand",
      "option_c": "Focus on current product optimization and delay API investment for 12 months",
      "option_d": "Limited API scope targeting top 3 requested integrations within 6 months",
      "optimal_choice": "B",
      "expert_analysis_text": "The phased approach balances strategic vision with execution reality. It delivers value incrementally, validates market demand, and maintains financial discipline while building toward the larger vision. This approach allows course-correction based on learnings and market response.",
      "rationale_for_a": "High-risk, high-reward but ties up significant resources without early validation or revenue generation.",
      "rationale_for_b": "Balances strategic investment with risk mitigation through incremental delivery and market validation.",
      "rationale_for_c": "Misses competitive window and ignores clear market signals from partners and business development.",
      "rationale_for_d": "Too narrow in scope, creates technical debt and doesn't establish platform foundation for future growth.",
      "peer_data_a": 22,
      "peer_data_b": 41,
      "peer_data_c": 15,
      "peer_data_d": 22
    },
    {
      "drill_id": "seed_045",
      "title": "International Market Entry Strategy",
      "target_pm_level": "Senior PM (5+ Yrs)",
      "skill_category": "Growth & Monetization",
      "core_scenario_text": "Your consumer app has 10M users in North America with $100M ARR. Three expansion opportunities emerged: Europe (high regulation, established competitors), Southeast Asia (growing market, low competition), and Latin America (familiar culture, economic volatility). You have resources for one market initially.",
      "stakeholder_1_role": "VP of Marketing",
      "stakeholder_1_quote": "Europe offers highest revenue potential but requires significant compliance and localization investment upfront.",
      "stakeholder_2_role": "Head of Growth",
      "stakeholder_2_quote": "Southeast Asia shows 40% year-over-year market growth with minimal local competition currently.",
      "stakeholder_3_role": "CFO",
      "stakeholder_3_quote": "Latin America has currency risks but lowest barrier to entry with our existing infrastructure.",
      "option_a": "Enter Europe with full compliance team and localized product offering",
      "option_b": "Target Southeast Asia with growth-focused strategy and local partnerships",
      "option_c": "Expand to Latin America leveraging existing Spanish localization capabilities",
      "option_d": "Pilot approach testing all three markets simultaneously with minimal investment",
      "optimal_choice": "B",
      "expert_analysis_text": "Southeast Asia offers the optimal risk-reward balance for expansion. High growth rates, limited competition, and partnership opportunities provide competitive advantage. While Europe has higher immediate revenue potential, the regulatory complexity and competition make it riskier for first international expansion.",
      "rationale_for_a": "High regulatory burden and established competition make this expensive with uncertain returns for initial expansion.",
      "rationale_for_b": "Strong growth market with first-mover advantage opportunity and manageable entry barriers through partnerships.",
      "rationale_for_c": "Economic volatility and currency risks could undermine expansion ROI despite cultural familiarity.",
      "rationale_for_d": "Spreads resources too thin across markets, preventing meaningful penetration or learning in any region.",
      "peer_data_a": 28,
      "peer_data_b": 38,
      "peer_data_c": 19,
      "peer_data_d": 15
    },
    {
      "drill_id": "seed_046",
      "title": "Legacy System Migration Priority",
      "target_pm_level": "Senior PM (5+ Yrs)",
      "skill_category": "Technical Acumen",
      "core_scenario_text": "Your platform runs on 8-year-old architecture causing 15% of support tickets and limiting new feature development. Migration would take 24 months, cost $3M, but improve performance 300% and reduce infrastructure costs 40%. New competitor launched similar service with modern architecture.",
      "stakeholder_1_role": "CTO",
      "stakeholder_1_quote": "Technical debt is strangling innovation; we must prioritize this migration before competitive gap widens further.",
      "stakeholder_2_role": "VP of Product",
      "stakeholder_2_quote": "Customers are requesting features we can't deliver; we're losing deals to competitors with better capabilities.",
      "stakeholder_3_role": "VP of Finance",
      "stakeholder_3_quote": "Infrastructure savings will pay for migration, but 24-month timeline with no new features seems risky.",
      "option_a": "Complete system migration as top priority with dedicated team over 24 months",
      "option_b": "Parallel development: migrate core systems while building new features on modern stack",
      "option_c": "Incremental migration focusing on highest-impact components first over 36 months",
      "option_d": "Build new product line on modern architecture while maintaining legacy system",
      "optimal_choice": "C",
      "expert_analysis_text": "Incremental migration reduces risk while maintaining feature delivery momentum. Starting with highest-impact components provides immediate value and learning opportunities. This approach maintains competitive positioning while systematically addressing technical debt without full business disruption.",
      "rationale_for_a": "All-or-nothing approach creates 24-month feature freeze, potentially losing competitive position entirely.",
      "rationale_for_b": "Parallel development increases complexity and resource strain without clear prioritization framework.",
      "rationale_for_c": "Risk-managed approach that delivers incremental value while maintaining competitive feature development.",
      "rationale_for_d": "Creates maintenance burden for two systems and doesn't address core technical debt issues.",
      "peer_data_a": 19,
      "peer_data_b": 25,
      "peer_data_c": 42,
      "peer_data_d": 14
    },
    {
      "drill_id": "seed_047",
      "title": "Acquisition Integration Strategy",
      "target_pm_level": "Senior PM (5+ Yrs)",
      "skill_category": "Stakeholder Management",
      "core_scenario_text": "Your company acquired a startup with complementary technology and 500K users. Integration options include full platform merge (18 months), separate brand operation (6 months), or hybrid approach. Acquired team prefers independence while executives want unified brand experience.",
      "stakeholder_1_role": "CEO",
      "stakeholder_1_quote": "We bought them for strategic value; customers should see unified experience reflecting our brand vision.",
      "stakeholder_2_role": "Acquired Company Founder",
      "stakeholder_2_quote": "Our users chose us specifically for our unique approach; integration risks losing our differentiation.",
      "stakeholder_3_role": "VP of Engineering",
      "stakeholder_3_quote": "Technical integration is complex but achievable; cultural integration poses bigger long-term challenges here.",
      "option_a": "Full platform integration with unified branding and shared user base within 18 months",
      "option_b": "Maintain separate brands while integrating backend systems and shared features",
      "option_c": "Keep acquisition independent with minimal integration for first year",
      "option_d": "Hybrid model: shared infrastructure with separate user experiences and branding",
      "optimal_choice": "D",
      "expert_analysis_text": "The hybrid model maximizes strategic value while minimizing integration risks. Shared infrastructure provides operational efficiencies and data synergies while preserving user experience differentiation. This approach allows gradual cultural integration and maintains both user bases during transition.",
      "rationale_for_a": "Aggressive timeline risks losing acquired users and creates unnecessary pressure on integration team dynamics.",
      "rationale_for_b": "Backend integration complexity without clear user experience strategy creates technical debt and confusion.",
      "rationale_for_c": "Minimal integration fails to realize acquisition synergies and strategic value that justified purchase.",
      "rationale_for_d": "Balances operational efficiency with user experience preservation while enabling gradual strategic alignment.",
      "peer_data_a": 23,
      "peer_data_b": 26,
      "peer_data_c": 12,
      "peer_data_d": 39
    },
    {
      "drill_id": "seed_048",
      "title": "Freemium Model Crisis",
      "target_pm_level": "Senior PM (5+ Yrs)",
      "skill_category": "Growth & Monetization",
      "core_scenario_text": "Your productivity app has 5M free users but only 3% convert to premium ($9.99/month). CAC is $15, LTV is $47. Free tier costs are escalating with AI feature usage. Investors want path to profitability, while user growth remains strong at 15% monthly but conversion has plateaued for six months.",
      "stakeholder_1_role": "CFO",
      "stakeholder_1_quote": "We're burning $2M monthly on infrastructure for free users. Either we dramatically improve conversion or we need usage-based pricing to make unit economics work.",
      "stakeholder_2_role": "VP of Growth",
      "stakeholder_2_quote": "Our viral coefficient is 1.3 because of the generous free tier. Any restrictions will kill organic growth and make our CAC unsustainable in competitive markets.",
      "stakeholder_3_role": "Head of Customer Success",
      "stakeholder_3_quote": "Premium users love unlimited AI features, but free users expect them now too. We surveyed churned trials - 67% said premium felt overpriced for incremental benefits they received.",
      "option_a": "Implement usage-based pricing with AI credits for all users, starting at $0 for basic usage",
      "option_b": "Reduce free tier limits significantly and add $4.99 starter tier with moderate AI access",
      "option_c": "Maintain free tier but add premium-only advanced AI features while raising price to $14.99",
      "option_d": "Create collaborative team features as premium differentiator while keeping individual AI features free",
      "optimal_choice": "A",
      "expert_analysis_text": "Usage-based pricing aligns costs with value delivery while maintaining growth potential. Starting at $0 preserves viral growth, while heavy AI users naturally graduate to paid tiers. This model scales with user engagement rather than arbitrary feature gates, improving unit economics without alienating the user base or disrupting organic growth patterns.",
      "rationale_for_a": "Aligns pricing with actual usage costs, maintains viral growth potential, and creates natural upgrade path as users increase engagement with valuable AI features.",
      "rationale_for_b": "Risks breaking viral growth mechanics that drive organic acquisition. Mid-tier pricing often creates confusion and may not sufficiently address infrastructure cost concerns.",
      "rationale_for_c": "Price increase without addressing core value perception issues likely reduces conversion further. Advanced AI features may not justify 50% price premium to existing user base.",
      "rationale_for_d": "Team features target smaller market segment and don't address individual user conversion problem or underlying infrastructure cost issues from AI usage.",
      "peer_data_a": 38,
      "peer_data_b": 23,
      "peer_data_c": 19,
      "peer_data_d": 20,
      "strategic_alternative": "D",
      "strategic_alternative_rationale": "Team-focused differentiation targets higher-value market segments and creates network effects within organizations. Valid strategy that addresses monetization through collaborative features while preserving individual user growth, though doesn't directly solve AI infrastructure cost pressures."
    }
];